### ISSUE TITLE
New function to convert between neuron id and skeleton id

### ISSUE THREAD

**Issue by mmc46** [natverse/rcatmaid#161]
Neuron id is in the output of the 'Export CSV' option in the Neuron Search widget, not skid.  
I'm finding users often generate this csv, and it would be useful to have a function that converts from neuron id to skeleton id.

**Comment by jefferis** [comment]
We have a function to do the reverse, catmaid_entities_from_models, which uses the `neurons/from-models` endpoint. Looks like this would need the `get-all-skeletons` endpoint which operates on one neuron at a time: https://github.com/catmaid/CATMAID/blob/2964e04e6e9772aff5d305e72c1b878030fe0e25/django/applications/catmaid/urls.py#L261

**Comment by tomka** [comment]
Because I needed to do bulk conversion of neuron IDs to skeleton IDs as well (in the CATMAID front-end), I recently added the `{project_id}/neurons/all-skeletons` API, which can operate on lists of neuron IDs: [urls.py definition](https://github.com/catmaid/CATMAID/blob/dev/django/applications/catmaid/urls.py#L268). For larger collections of neuron IDs this should be faster than individual look-ups. This is only part of the `dev` branch yet though and deployed only to the itanna.io server, but not yet neuropil (or VFB I suppose).
